# Generated by Django 4.2.5 on 2023-09-11 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 13, 33, 42, 912085, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 13, 33, 42, 911804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
