# Generated by Django 4.2.5 on 2023-09-14 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_date_created_alter_todolist_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='number_of_tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 9, 57, 4, 231120, tzinfo=datetime.timezone.utc)),
        ),
    ]
